
[project]
name = "wepy"
description = "Weighted Ensemble Framework"
readme = { "file" = "README.md", "content-type" = "text/plain" }
license = "MIT"
requires-python = ">=3.11"

authors = [
  { name = "Samuel Lotz", email = "samuel.lotz@salotz.info" },
  { name = "Alex Dickson", email = "alexrd@msu.edu" },
  { name = "Tom Dixon" },
  { name = "Robert Hall" },
  { name = "Nicole Roussey" },
]
version = "1.1.0"

classifiers = [
  "Topic :: Utilities",
  "License :: OSI Approved :: MIT License",
  "Programming Language :: Python :: 3",
]

dependencies = [
  "attrs",
  "immutables",
  "numpy>=2",
  "nptyping",
  "h5py>=3",
  "networkx",
  "pandas",
  "click",
  "scipy",
  "geomm",
  "tabulate",
  "jinja2",
  "pint",
  "more-itertools",
]

[project.optional-dependencies]

md = [
  "mdtraj",
  "openmm_systems==0.0.0",
  # NOTE: you should just install this yourself to get it the compute
  # runtime you need.
  "openmm",
  # for dealing with openmm serialized objects
  "lxml",
]

distributed = [
  "ray",
]

prometheus = [
  "prometheus_client",
  "pympler",
]

graphics = [
  "matplotlib",
  # NOTE: pillow only needed for matplotlib but it needs to be above this
  # version for security reasons. If matplotlib also adds these constraints this
  # can be removed
  "pillow>=10.0.1",
]

[project.urls]

Documentation = "https://adicksonlab.github.io/wepy/index.html"
Source = "https://github.com/ADicksonLab/wepy"
Issues = "https://github.com/ADicksonLab/wepy/issues"

[build-system]
requires = ["uv_build>=0.9.11,<0.10.0"]
build-backend = "uv_build"

[dependency-groups]

dev = [
  # testing
  "pytest",
  "coverage",
  "pytest-cov",
  # for documentation testing
  "pytest-shutil",
  "pytest-check",
  "pytest-datadir @ git+https://github.com/salotz/pytest-datadir-extras.git@41e9a1e94ba27efe28ce9d0019b1e0a73be34400",
  "pytest-print",
  "pytest-timeout",
  "pytest-rerunfailures",
  "pytest-flakefinder",
  # for testing openmm wrappers
  "lxml",
  "psutil",
  # qa
  "black",
  "isort",
  "ruff",
  "interrogate",
  # typechecking
  "mypy",
  # interactive
  "ipython",
  "pdbpp",
  # docs
  "sphinx",
  "sphinxcontrib-napoleon",
  "sphinxcontrib-newsfeed",
  "sphinxcontrib-bibtex",
  "sphinxcontrib-newsfeed",
  "nbsphinx",
  "notebook",
]

[tool.interrogate]

fail-under = 100
verbose = 2

[tool.pytest]

minversion = "9.0"
strict = true

addopts = [
    "--import-mode=importlib",
    "--timeout_method=thread",
    # Global timeout just in case something goes wrong. You should set
    # specific timeouts for known problematic tests
    "--timeout=300",
]

python_classes = ["Test*", "Test_*"]
python_functions = ["test_*"]
python_files = ["test_*.py"]

markers = [
   "ray", # mark a test as running ray
]

log_level = "INFO"

[tool.mypy]

pretty = true
color_output= true

[[tool.mypy.overrides]]
module = "mdtraj.*"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "openmm.*"
ignore_missing_imports = true
